#!/usr/bin/env python3
"""Regenerate the file-icon lookup tables from a VS Code icon-theme JSON.

The theme file names an icon per extension, per exact filename, and per folder
name, indirected through `iconDefinitions`. Resolving that indirection here,
rather than at runtime, means Winter ships sorted `&str` tables it can binary
search instead of a JSON document it has to parse at startup.

Usage:
    scripts/gen-icon-map.py <icon-theme.json> > crates/winter-term/src/icons/map.rs
"""

import json
import os
import re
import sys

BANNER = "=" * 72

HEADER = f"""//! File-type icon lookup tables.
//!
//! Generated by `scripts/gen-icon-map.py` from a VS Code icon-theme JSON. Do
//! not edit by hand: rerun the script instead. Every name here is the stem of
//! a file under `assets/icons/file/`, which `build.rs` packs into the binary.
//!
//! Each table is sorted by key so the lookups can binary search.

// {BANNER}
// Constants
// {BANNER}
"""


def load_theme(path):
    """Parse the theme, which is JSON with line comments and trailing commas."""
    text = open(path, encoding="utf-8").read()
    text = re.sub(r"//.*?$", "", text, flags=re.M)
    text = re.sub(r",(\s*[}\]])", r"\1", text)
    return json.loads(text)


def stem_of(definitions, key):
    """The icon file's stem for an `iconDefinitions` key, or None."""
    entry = definitions.get(key)
    if not entry or "iconPath" not in entry:
        return None
    return os.path.splitext(os.path.basename(entry["iconPath"]))[0]


def table(name, doc, pairs):
    lines = [f"/// {doc}", f"pub(crate) static {name}: &[(&str, &str)] = &["]
    for key, value in sorted(pairs):
        lines.append(f'    ({key!r}, {value!r}),'.replace("'", '"'))
    lines.append("];")
    return "\n".join(lines)


def constant(name, doc, value):
    return f'/// {doc}\npub(crate) static {name}: &str = "{value}";'


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    theme = load_theme(sys.argv[1])
    definitions = theme.get("iconDefinitions", {})

    def resolved(mapping):
        out = []
        for key, definition in mapping.items():
            stem = stem_of(definitions, definition)
            if stem:
                out.append((key.lower(), stem))
        return out

    parts = [HEADER]
    for name, doc, key, fallback in [
        ("DEFAULT_FILE", "Drawn for a file no table matches.", "file", "default_file"),
        ("DEFAULT_FOLDER", "Drawn for a collapsed directory no table matches.", "folder", "default_folder"),
        ("DEFAULT_FOLDER_OPEN", "Drawn for an expanded directory no table matches.", "folderExpanded", "default_folder_opened"),
    ]:
        parts.append(constant(name, doc, stem_of(definitions, theme.get(key, "")) or fallback))

    parts.append(table(
        "FILE_EXTENSIONS",
        "Icon stem by lowercase file extension, without the dot.",
        resolved(theme.get("fileExtensions", {})),
    ))
    parts.append(table(
        "FILE_NAMES",
        "Icon stem by exact lowercase filename, which wins over the extension.",
        resolved(theme.get("fileNames", {})),
    ))
    parts.append(table(
        "FOLDER_NAMES",
        "Icon stem by exact lowercase directory name.",
        resolved(theme.get("folderNames", {})),
    ))
    print("\n\n".join(parts))


if __name__ == "__main__":
    main()
