//! Embeds the Windows executable icon, and packs the bundled SVG icon set.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use flate2::write::DeflateEncoder;
use flate2::Compression;
#[cfg(windows)]
use winresource::WindowsResource;

// Constants

// Only Windows PE binaries carry an icon resource; other platforms ship the
// icon separately (see assets/icons and crates/winter-term/Cargo.toml's
// package.metadata.deb).
#[cfg(windows)]
const ICON_PATH: &str = "assets/icons/winter-terminal.ico";

/// Icon sets packed into the binary, each a directory of `.svg` files under
/// `assets/icons/`. A name is the file's stem, prefixed by its set.
const ICON_SETS: [&str; 2] = ["file", "git"];

/// Name of the packed payload written into `OUT_DIR`.
const BLOB_NAME: &str = "icons.blob";

/// Name of the generated index written into `OUT_DIR`.
const INDEX_NAME: &str = "icons_index.rs";

fn main() {
    #[cfg(windows)]
    WindowsResource::new()
        .set_icon(ICON_PATH)
        .compile()
        .expect("failed to embed Windows icon resource");

    pack_icons();
}

/// Deflate every bundled SVG into one payload, and write the sorted
/// name-to-slice index beside it.
///
/// Each icon is compressed on its own rather than the set being compressed as a
/// whole, so drawing one icon inflates only that icon (a kilobyte or two)
/// instead of unpacking eight megabytes to reach it. The payload is generated
/// rather than checked in so the repository keeps the readable SVGs, while the
/// binary carries them at about a fifth of the size.
fn pack_icons() {
    let out_dir =
        PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set for build scripts"));
    let assets = Path::new("assets/icons");

    let mut blob: Vec<u8> = Vec::new();
    let mut index: Vec<(String, usize, usize, usize)> = Vec::new();

    for set in ICON_SETS {
        let dir = assets.join(set);
        println!("cargo:rerun-if-changed={}", dir.display());
        let mut entries: Vec<PathBuf> = fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
            .map(|entry| entry.expect("a readable directory entry").path())
            .filter(|path| path.extension().is_some_and(|ext| ext == "svg"))
            .collect();
        entries.sort();

        for path in entries {
            let stem = path
                .file_stem()
                .expect("an .svg path has a stem")
                .to_string_lossy()
                .to_string();
            let raw = fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
            let mut encoder = DeflateEncoder::new(Vec::new(), Compression::best());
            encoder
                .write_all(&raw)
                .expect("deflating into a Vec cannot fail");
            let packed = encoder.finish().expect("deflating into a Vec cannot fail");
            index.push((format!("{set}/{stem}"), blob.len(), packed.len(), raw.len()));
            blob.extend_from_slice(&packed);
        }
    }

    index.sort_by(|a, b| a.0.cmp(&b.0));

    let mut source = String::from(
        "// Generated by build.rs. Each entry is (name, offset, packed length, \
         inflated length), sorted by name.\n\
         pub(crate) static ICON_INDEX: &[(&str, u32, u32, u32)] = &[\n",
    );
    for (name, offset, packed, raw) in &index {
        source.push_str(&format!("    ({name:?}, {offset}, {packed}, {raw}),\n"));
    }
    source.push_str("];\n");

    fs::write(out_dir.join(BLOB_NAME), &blob).expect("writing the icon payload");
    fs::write(out_dir.join(INDEX_NAME), source).expect("writing the icon index");
}
